version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
