version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tonne_network
volumes:
  pgdata:
networks:
  tonne_network:
    driver: bridge
    external: true
